### ISSUE TITLE
ISSUE: The "Legacy" `Livepeer-Community-Node/Grant-Program` Repo

### ISSUE THREAD

**Issue by criticaltv** [livepeer/Grant-Program#11]
There exists a very similar repo to `this.repo` here:

> https://github.com/Livepeer-Community-Node/Grant-Program

`this.repo` doesn't appear to be a fork of the above repo, plus there are a load of open issues here:

> https://github.com/Livepeer-Community-Node/Grant-Program/issues

And closed ones, here:

> https://github.com/Livepeer-Community-Node/Grant-Program/issues?q=is%3Aissue+is%3Aclosed

This issue is to track the progress of effort required to the success metrics for the Grant Program of:

- [x] Approve / Reject > 90% of all applications made for funding
- [x] Spend 25% of funds before end of Q1 (current stake is 175124 LPT)
- [x] Get 3 positive case studies from the "Grant Program" before end of H1

I know that the "Livepeer-Community-Node" was under a previous administration, but there are ideas, and enthusiasm from "the community" which have not been addressed.

**Comment by ericxtang** [comment]
Hi @criticaltv,
Thanks for filing this issue.  The previous `Livepeer-Community-Node/Grant-Program` repo is migrated over to the current repo because we wanted to kick start the new grants program with the new committee.  We feel that the new committee based approach will provide a more transparent process.  Is there any specific issue from the old repo you would like to migrate over?  I have updated the readme to link back to the old repo for documentation purposes.

Can you give some reference to the success metrics for the Grant Program?  I don't remember the committee has represented the 3 points listed here.  However, if you would like to propose the committee to have a few success metrics, we welcome the suggestions!  I think `Approve / Reject > 90% of all applications made for funding` and `Get 3 positive case studies from the "Grant Program" before end of H1` are both good candidates.

**Comment by criticaltv** [comment]
Every issue raised in that repo, whether by me, or someone else, represents an expression of interest in building on Livepeer.

When I last checked, there were 11 open issues - ones which have either not been funded, or not been approved.

These 11 present opportunities to test the new committee-based approach on real-life proposals, and to develop the Grant Programme's abilities in openly and transparently responding to applications.

This can have a real positive effect in helping future applicants understand "the kind of thing" that this Livepeer Core internal committee agrees to fund, and more crucially, for those it *does not* agree to fund, and the reasons why.

**Comment by criticaltv** [comment]
As for the success metrics for the Grant Program, you are welcome to use these suggestions, but it's probably best that your committee define these for yourselves.

Also, seems odd to be encouragig applicants to define success metrics, when the committee itself doesn't have their own success metrics agreed and published :)

**Comment by ericxtang** [comment]
The committee has drafted a proposal for its [success metrics](https://github.com/livepeer/Grant-Program/issues/14).  Feedback welcomed :)
