### ISSUE TITLE
Wish List: Pricing Visibility Data + Interface

### ISSUE THREAD

**Issue by dob** [livepeer/Grant-Program#2]
**The Problem**
Potential broadcasters, token holding delegators, and orchestrators have no easy visibility into the prices that nodes are currently charging to do transcoding work on the network.

**Potential Solutions**
Propose a tool that would provide this visibility to everyone on the network. Ideally if this tool existed, anyone can answer the questions:

1. What prices were paid for recently completed work?
2. What price is each active orchestrator node currently charging?

There are probably two different ways that this visibility could be provided, each with their own benefits:

* Raw data - imagine daily or hourly feeds of the prices that each node on the network were currently advertising, and feeds of all the inferred prices that were paid for recent work. This raw data could be used to build great visualizations, alerts, or any creative applications that people wanted.
* Easily consumable user interface - Summary report that lives on a web page or CLI tool that makes it easy for someone to understand pricing at a glance. 

**Challenges**

* Pricing information does not exist on chain. You would likely have to ping each orchestrator node at some interval asking for pricing information and aggregate the results yourself.
* When payments are cashed in it doesn't reveal pricing information. You may be able to infer it from the parameters of the micropayment tickets combined with the pricing information captured via polling above to make a "best guess". 

**Summary**
We'd love to support people working on building tools that give this visibility to the ecosystem. Share your questions or ideas here, and feel free to make a proposal of your own, or schedule some time to chat with team members about your ideas.

**Comment by Saumay-Agrawal** [comment]
Hi @dob, I would love to work on this idea. I've been researching on Livepeer since January, and have come up with a solution for this problem of Price Visibility.

<br/>

# Overview
The Livepeer network contains various nodes (broadcasters, delegators, orchestrators/transcoders, and end-users), which work together to constitute a decentralized streaming service. The orchestrators/transcoders are the heart of this network. These nodes handle the video transcoding operations and help the broadcasters in reaching out to users across various platforms. However, there doesn’t exist a solution for getting an overview of prices and fees being charged for the transcoding process in the network. We aim to fill this void via the development of a Price Monitoring Tool for the network. The tool will be built around but not be limited to metrics like “price per unit”, “pixels per unit”, “number of pixels encoded” etc.

<img width="653" alt="Infrastructure Overview" src="https://user-images.githubusercontent.com/24296199/74735097-f8615100-5275-11ea-8931-505be9c611f1.png">

<br/>

# Deliverables

1. An always up-to-date database of fees and pricing information for various orchestrators, along with their transcoding job histories.
2. A GraphQL based API, coherent with the existing Livepeer API hosted on The Graph, for exposing various analytics related to the fees and pricing.
3. The Pricing Tool, a web application showcasing the pricing status and history in the Livepeer network through visualizations and insight provoking UI components.
4. Tutorial and guides demonstrating the workflow of the tool.
5. A well-documented, human-readable codebase that is in coherence with the existing Livepeer codebase.

<br/>

# Roadmap

## Phase 1 - Research Phase
This phase has already been completed before submitting the proposal.

## Phase 2 - Data Aggregation (2 Weeks)
Under this phase, the problem of raw data will be solved. The necessary steps will include:

- Get vantage on the various API endpoints required for data collection, testing them by collecting sample data points and design the database schema accordingly.
- Determine the frequency of data collection for each API endpoint. 
- Writing scripts to aggregate data from the API endpoints identified above at corresponding time intervals and save it in the database (MongoDB).

End result - a one-stop-shop database for all the data related to the Fees and Pricing involved in the transcoding process.

## Phase 3 - Data Analytics (2 Weeks)
In this phase, the foundation of entire analytics involved in the Pricing Tool will be laid down. The key activities include:

- Identifying what insights can be drawn from the raw data collected as a part of the previous phase.
- Discussion with the community on the same. Take inputs from the community on what other insights they would like to see.
- Implement an analytics layer in the form of a GraphQL API consisting of various wrapper functions, each designed to perform a specific analysis by fetching data from the database.

End result - An API for directly accessing various analytics related to Fees and Pricing involved in the transcoding process.

## Phase 4 - Data Visualisation (4 Weeks)

In this phase, the Pricing Tools dashboard will be implemented. Key steps include:

- Mockup generation for the dashboard based on the analytics possible on the data.
- Community discussions on the same
- Implementation of the front-end component of the Pricing Tool dashboard. This will be achieved by implementation of mockup components using React and connecting them to the GraphQL API developed in Phase 3.
- Video Tutorials + User guides for using the tool.

End result - A pricing tool that enhances the relationship between the broadcasters and the orchestrators. 

## Phase 5 - Q/A and Bug Fixes (2 Weeks)

- Q/A to ensure robustness and desired accessibility
- Eradication of bugs found during community usage.
- Product iterations based on the feedback from community.

<br/>

# Maintenance Plans

- After project completion, maintaining and iterating on user feedback on the system actively for the T+3 months. That means bug fixes, upgrading API endpoints to keep the tool up and running with the specs mentioned in the current proposal.
- For 1 year: support if the system goes down.

<br/>

# Upgrade Plans

- We have plans to build a more comprehensive tool for getting an insight into the Livepeer network.
- This comprehensive tool will incorporate the proposed Pricing Tool as a part of it, and follow a similar design pattern.
- The aforementioned tool will also address the RFP of [Infrastructure Management tools](https://github.com/livepeer/Grant-Program/issues/3).
- Apart from this, the tool will add analytics components for the Delegator-Orchestrator relationship as well, which at present is not a part of the existing Livepeer Explorer. (A concern raised in the 13th Feb community call)

<br/>

# Total Budget Requested

Phase | Time (weeks) | Budget | Amount in LPT*
-- | -- | -- | --
1 | - | $ 0 | 0 LPT
2 | 2 | $5,000 | 3125 LPT
3 | 2 | $5,000 | 3125 LPT
4 | 4 | $8,000 | 5000 LPT
5 | 2 | $2,000 | 1250 LPT
Total | 10 | $20,000 | 12500 LPT

* 1 LPT = 1.6 USD (as of exchange rate on 18th February, 2020 3:00 pm IST)  

<br/>

# Team

## Contact Info
Email: saumay@thevantageproject.com

## About the Team
Our team comprises of people having a background in theory-based visual design and analytical methods. We like to discover and validate insights from data, then translate them into systems, processes, and frameworks that help in mindfully created human-information interactions.

The advent of high technology information, imaging, networking, mobile devices, and social media systems has fostered a modern renaissance in visualization. Just as the great artists of the European Renaissance were also designers, inventors, scientists & architects, we think the modern visualizers have an essential role to play in decoding the increasingly complex world and make it accessible to all humans.

Curiosity led us down the blockchain ecosystem rabbit hole. We wanted to analyze the organic activity happening on these public blockchains but the reality is that the format of these public datasets make it very difficult to analyze, understand and then derive insights.

Hence, we want to build tools that can help in solving this problem and give users means to make informed decisions without relying on any third party. Visualizations are one part of this toolkit.

Team Website: https://www.thevantageproject.com/buidl/

## Team Members

1. Saumay
    - Livepeer Researcher and Lead Developer
    - Extensive experience in wrangling data and building ETL pipelines.
    - [Github](https://github.com/Saumay-Agrawal), [LinkedIn](https://www.linkedin.com/in/saumayagrawal/)
2. Abhinav
    - Designer and Frontend developer
    - Have experience in designing HCI solutions especially in the domain of data analytics.
    - [Github](https://github.com/AbhinavThukral97), [LinkedIn](https://www.linkedin.com/in/thukralabhinav/)
3. Prastut
    - Project Manager
    - Has 5+ years of product-dev experience across multiple startups, research labs and companies. Will     help the team with nuances on how to best visualize data from end user PoV leveraging the experience picked up through the following projects:
          - Architected [Polkaviz](http://polkavizproject.surge.sh/) project.
          - Built the entire frontend data visualization stack for [Centify](https://centify.surge.sh/#/).
          - Was a data visualization research associate at Information Design Lab, IIT Bombay. [Work documentation](https://prastut.github.io/dataviz).
    - [Github](https://github.com/prastut), [LinkedIn](https://www.linkedin.com/in/prastut/)

## #ProofOfWork
Similar projects Github repo links:
- [PolkaAnalytics](https://github.com/thevantageproject/PolkaAnalytics)
- [ZCash Service Status Dashboard](https://github.com/thevantageproject/zcash_service_status_dashboard)
You can check out our [Github profile](https://github.com/thevantageproject/) as well.

**Comment by dob** [comment]
@Saumay-Agrawal Thanks so much for this proposal. I have some feedback and questions. Mind copying the proposal into a new issue so that there can be a thread dedicated specifically to your concept?

**Comment by Saumay-Agrawal** [comment]
@dob Thanks for the appreciation! I have created a new issue, where you can give your feedback, and ask all your doubts regarding the proposal.
