### ISSUE TITLE
Livepeer Academy Discretionary Bounty Fund

### ISSUE THREAD

**Issue by Titan-Node** [livepeer/Grant-Program#38]
**Give a 3 sentence description about this proposal.**
While engaging with the community I find there are plenty of low cost solutions that come up in conversation that are usually not big enough to apply for a grant application. These are usually $50 bounties that could take <1 hour to complete and would provide huge value to the community.

Here are some examples of these types of conversations (just in the past week):
 - A flow chart of how Data flows back and forth between B/O/T's
 - Content around benchmarking and performance
 - Content around pools and scaling an Orchestrator
- A Discord Bot to connect common errors linked in Discord to Github repos that have already solved this
- A script to restart Os after crashing
- The list goes on and on

**Describe the problem you are trying to solve** 
These types of micro bounties/solutions need to be encouraged within the Livepeer eco-system and managing these small bounties as the Community Grants Node may be cumbersome and low value for time.

**Describe the solution you are proposing.** 
I propose a discretionary spending budget provided to the Livepeer Academy (Run by Titan Node) that can award $50 bounties (1 LPT) to these types of small budget solutions.

To start, this would be a small budget of 5 LPT provided to the [Livepeer Academy Node](https://explorer.livepeer.org/accounts/0x5d11abd838073df76e32c495f97fd3239eabb9fb/campaign) with a purpose to spend, at it's discretion, on bounties and improvements that would benefit all things Livepeer.

Linked is also a spreadsheet of all the bounties and expenses that would be paid out by the Livepeer Academy and records of the use of funds. Link to the tracker is [here](https://docs.google.com/spreadsheets/d/1G9bzUJu0pNBfn97ePOqFK1eylkTgUXw-BVQz3GX18S4/edit?usp=sharing)

Thank you for your consideration 
Titan Node / Livepeer Academy

**Comment by papabear99** [comment]
Here's a freebie that I was supposed to write last week.

The first paragraph is adapted from a post by Yondon.  The follow comments address misconceptions I see in Discord on a regular basis.


The purpose of the test streams is to give orchestrators and delegators an initial sense of how orchestrators will perform for streams ingested in a particular region (note: since the tests involve only a single short stream they do not currently attempt to measure capacity). While good performance on these tests does not necessarily mean that an orchestrator will receive a lot of real work, it can serve as a signal of how an orchestrator _could_ perform if it received real work. 

Contrary to the belief of many orchestrator operators test scores are not included in the job selection algorithm and have no direct bearing on whether or how much work an orchestrator receives.

The way the selection process works is, when a broadcaster sends out a request the first 8 orchestrators to respond are put into the "active pool" and then a stake weighted selection is made from the active set of orchestrators to determine which orchestrator will receive the work.

**Comment by nelsorya** [comment]
Hey @Titan-Node, sorry for the delay in responding to this one. I believe there may have been some back and forth on this over dm's back when this was posted, but we should have followed up here. We decided not to fund this proposal. While we support the sentiment of the proposal, we want to avoid creating additional grant pools even for smaller amounts. Ultimately we feel that trying to value every small contribution is difficult to scale and adding a second micro-grants program is confusing for those applying for grants
